"""Seed content: construct library, question bank and the normalized
Career Knowledge System.

Derived from PRD sections 10 (Student Intelligence Engine), 11
(Recommendation System) and 13 (Career Knowledge System).

The career data is split into reusable registries (SKILLS, SUBJECTS,
INDUSTRIES, TOOLS) and the CAREERS list, which references them by name and adds
structured traits, responsibilities, education steps and career relations.
``init_db`` normalizes this into the relational tables.
"""

# --------------------------------------------------------------------------- #
# Assessment constructs & question bank (unchanged)
# --------------------------------------------------------------------------- #
CONSTRUCTS = {
    "Cognitive": ["analytical_thinking", "problem_solving", "numerical_reasoning"],
    "Interests": ["technology", "business", "healthcare", "arts"],
    "Personality": ["conscientiousness", "openness", "extraversion"],
    "Values": ["income", "security", "helping_others"],
    "Work Preferences": ["leadership", "teamwork", "entrepreneurship"],
}

CONSTRUCT_LABELS = {
    "analytical_thinking": "Analytical Thinking",
    "problem_solving": "Problem Solving",
    "numerical_reasoning": "Numerical Reasoning",
    "technology": "Technology Interest",
    "business": "Business Interest",
    "healthcare": "Healthcare Interest",
    "arts": "Arts & Creativity",
    "conscientiousness": "Conscientiousness",
    "openness": "Openness",
    "extraversion": "Extraversion",
    "income": "Income Orientation",
    "security": "Security Orientation",
    "helping_others": "Helping Others",
    "leadership": "Leadership",
    "teamwork": "Teamwork",
    "entrepreneurship": "Entrepreneurship",
}

# Question bank. Two Likert items per construct (some reverse-scored).
# value scale: 1 (Strongly disagree) .. 5 (Strongly agree)
QUESTIONS = [
    ("Q-AT-1", "I enjoy breaking complex problems into smaller parts to understand them.", "analytical_thinking", "Cognitive", False),
    ("Q-AT-2", "I prefer to act on gut feeling rather than carefully analysing a situation.", "analytical_thinking", "Cognitive", True),
    ("Q-PS-1", "I keep trying different approaches until I solve a difficult problem.", "problem_solving", "Cognitive", False),
    ("Q-PS-2", "I get stuck and give up quickly when a problem has no obvious solution.", "problem_solving", "Cognitive", True),
    ("Q-NR-1", "I am comfortable working with numbers, data and statistics.", "numerical_reasoning", "Cognitive", False),
    ("Q-NR-2", "Mathematical or quantitative tasks make me anxious.", "numerical_reasoning", "Cognitive", True),
    ("Q-TE-1", "I like understanding how computers, software or gadgets work.", "technology", "Interests", False),
    ("Q-TE-2", "I enjoy building, coding or tinkering with technology.", "technology", "Interests", False),
    ("Q-BU-1", "I am interested in how companies make money and grow.", "business", "Interests", False),
    ("Q-BU-2", "I enjoy negotiating, selling or persuading others.", "business", "Interests", False),
    ("Q-HC-1", "I am drawn to caring for people's health and well-being.", "healthcare", "Interests", False),
    ("Q-HC-2", "I find biology and the human body fascinating.", "healthcare", "Interests", False),
    ("Q-AR-1", "I enjoy creative activities like design, writing, music or art.", "arts", "Interests", False),
    ("Q-AR-2", "I often come up with original or imaginative ideas.", "arts", "Interests", False),
    ("Q-CO-1", "I plan my work carefully and meet deadlines.", "conscientiousness", "Personality", False),
    ("Q-CO-2", "I often leave tasks unfinished or get disorganised.", "conscientiousness", "Personality", True),
    ("Q-OP-1", "I enjoy exploring new ideas and unfamiliar experiences.", "openness", "Personality", False),
    ("Q-OP-2", "I prefer routine and dislike change.", "openness", "Personality", True),
    ("Q-EX-1", "I feel energised when interacting with lots of people.", "extraversion", "Personality", False),
    ("Q-EX-2", "I prefer working quietly on my own rather than in groups.", "extraversion", "Personality", True),
    ("Q-IN-1", "A high salary is very important to me when choosing a career.", "income", "Values", False),
    ("Q-IN-2", "I would happily take meaningful work even if it paid less.", "income", "Values", True),
    ("Q-SE-1", "Job stability and security matter a lot to me.", "security", "Values", False),
    ("Q-SE-2", "I am comfortable with uncertainty and risk in my career.", "security", "Values", True),
    ("Q-HO-1", "I want my work to make a positive difference in people's lives.", "helping_others", "Values", False),
    ("Q-HO-2", "Helping others is one of my main motivations.", "helping_others", "Values", False),
    ("Q-LE-1", "I like taking charge and leading a team toward a goal.", "leadership", "Work Preferences", False),
    ("Q-LE-2", "I would rather follow than be responsible for leading others.", "leadership", "Work Preferences", True),
    ("Q-TW-1", "I do my best work collaborating closely with others.", "teamwork", "Work Preferences", False),
    ("Q-TW-2", "I enjoy contributing to a shared team result.", "teamwork", "Work Preferences", False),
    ("Q-EN-1", "I dream of starting my own venture or business one day.", "entrepreneurship", "Work Preferences", False),
    ("Q-EN-2", "I am willing to take risks to pursue a new opportunity.", "entrepreneurship", "Work Preferences", False),
]

# --------------------------------------------------------------------------- #
# Career Knowledge System — reusable registries
# --------------------------------------------------------------------------- #

# Skill master vocabulary: name -> (category, description)
SKILLS = {
    "Statistics": ("Cognitive", "Summarising and inferring from data"),
    "Python/R": ("Technical", "Programming for data and analysis"),
    "Machine learning": ("Technical", "Building models that learn from data"),
    "Data visualisation": ("Technical", "Communicating data visually"),
    "Critical thinking": ("Cognitive", "Reasoning carefully about evidence"),
    "Programming": ("Technical", "Writing and maintaining software"),
    "Problem solving": ("Cognitive", "Working through difficult problems"),
    "System design": ("Technical", "Architecting reliable software systems"),
    "Collaboration": ("Interpersonal", "Working effectively with others"),
    "Advanced mathematics": ("Cognitive", "Higher mathematics and proofs"),
    "Deep learning": ("Technical", "Neural-network modelling"),
    "Research methodology": ("Cognitive", "Designing rigorous experiments"),
    "Biology knowledge": ("Domain", "Understanding living systems"),
    "Empathy": ("Interpersonal", "Understanding others' feelings"),
    "Decision making": ("Cognitive", "Choosing well under uncertainty"),
    "Communication": ("Interpersonal", "Explaining ideas clearly"),
    "Patient care": ("Domain", "Caring for patients' needs"),
    "Teamwork": ("Interpersonal", "Contributing to a shared goal"),
    "Attention to detail": ("Cognitive", "Catching errors and details"),
    "Active listening": ("Interpersonal", "Listening to understand fully"),
    "Research": ("Cognitive", "Investigating questions systematically"),
    "Risk taking": ("Business", "Acting decisively under uncertainty"),
    "Leadership": ("Interpersonal", "Guiding teams toward goals"),
    "Selling": ("Business", "Persuading and closing deals"),
    "Resilience": ("Interpersonal", "Recovering from setbacks"),
    "Analytical thinking": ("Cognitive", "Breaking down complex problems"),
    "Data literacy": ("Cognitive", "Interpreting data correctly"),
    "Domain knowledge": ("Domain", "Deep understanding of a field"),
    "Empathy for users": ("Interpersonal", "Understanding user needs"),
    "Creativity": ("Creative", "Generating original ideas"),
    "Data analysis": ("Cognitive", "Drawing insight from data"),
    "Persuasion": ("Interpersonal", "Influencing others' decisions"),
    "Visual design": ("Creative", "Designing appealing visuals"),
    "Visual design tools": ("Technical", "Using professional design software"),
    "Patience": ("Interpersonal", "Staying calm and persistent"),
    "Subject expertise": ("Domain", "Mastery of a subject area"),
    "Mathematics": ("Cognitive", "Applying mathematical methods"),
    "Project management": ("Business", "Planning and delivering projects"),
    "Numerical reasoning": ("Cognitive", "Reasoning with numbers"),
    "Integrity": ("Interpersonal", "Acting honestly and ethically"),
    "Analysis": ("Cognitive", "Examining information methodically"),
}

SUBJECTS = [
    "Mathematics", "Computer Science", "Statistics", "Physics", "Biology",
    "Chemistry", "Psychology", "Business Studies", "Economics", "English",
    "Art", "Design", "Accounting", "Education", "Any subject specialism",
]

INDUSTRIES = [
    "Technology", "Software", "Artificial Intelligence", "Healthcare",
    "Mental Health", "Finance", "Consulting", "Startups", "Marketing",
    "Design", "Education", "Construction", "Research", "Professional Services",
]

TOOLS = [
    "Python", "R", "SQL", "Excel", "Figma", "AutoCAD", "Jupyter",
    "TensorFlow", "PowerPoint", "Tableau", "Git", "Jira",
]


def _skills(*pairs):
    """Helper: build skill links as (name, importance) with a gentle decay
    default when importance is omitted."""
    out = []
    for i, p in enumerate(pairs):
        if isinstance(p, tuple):
            out.append(p)
        else:
            out.append((p, round(max(0.5, 0.9 - i * 0.1), 2)))
    return out


# --------------------------------------------------------------------------- #
# Careers — core fields + references into the registries above
# --------------------------------------------------------------------------- #
# traits: {construct: ideal_score}. importance defaults to ideal_score on seed,
# preserving the original recommendation business logic exactly.
CAREERS = [
    {
        "slug": "data-scientist", "name": "Data Scientist",
        "category": "Technology", "subcategory": "Data & AI",
        "summary": "Turns data into predictions and decisions.",
        "description": "Data scientists analyse large datasets to uncover patterns and build predictive models that help organisations make decisions.",
        "difficulty_level": "Advanced", "work_environment": "Office / Remote",
        "salary_range": "High", "outlook": "Excellent — growing rapidly",
        "remote_friendly": True, "education_level": "Bachelor's (often Master's)",
        "skills": _skills("Statistics", "Python/R", "Machine learning", "Data visualisation", "Critical thinking"),
        "subjects": ["Mathematics", "Computer Science", "Statistics"],
        "industries": ["Technology", "Artificial Intelligence"],
        "tools": ["Python", "SQL", "Jupyter", "Tableau"],
        "traits": {"analytical_thinking": 0.95, "problem_solving": 0.9, "numerical_reasoning": 0.95,
                   "technology": 0.85, "openness": 0.7, "conscientiousness": 0.7},
        "responsibilities": [
            ("Clean and explore data", "Prepare messy data and study its structure.", 0.9),
            ("Build and evaluate machine-learning models", "Train, tune and validate predictive models.", 0.85),
            ("Communicate insights to stakeholders", "Translate findings into clear recommendations.", 0.7),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Mathematics, Computer Science, Statistics", False),
            ("degree", "Undergraduate degree", "Bachelor's in Computer Science, Statistics or Mathematics", False),
            ("masters", "Specialisation", "Master's or focused data-science training", True),
        ],
        "relations": [("software-engineer", "similar"), ("ai-researcher", "progression"), ("business-analyst", "alternative")],
    },
    {
        "slug": "software-engineer", "name": "Software Engineer",
        "category": "Technology", "subcategory": "Software Development",
        "summary": "Designs and builds the software that powers modern life.",
        "description": "Software engineers design, build and maintain the applications and systems that power modern life.",
        "difficulty_level": "Intermediate", "work_environment": "Office / Remote",
        "salary_range": "High", "outlook": "Excellent",
        "remote_friendly": True, "education_level": "Bachelor's",
        "skills": _skills("Programming", "Problem solving", "System design", "Collaboration"),
        "subjects": ["Computer Science", "Mathematics"],
        "industries": ["Technology", "Software"],
        "tools": ["Python", "SQL", "Git"],
        "traits": {"analytical_thinking": 0.85, "problem_solving": 0.95, "technology": 0.95,
                   "numerical_reasoning": 0.7, "teamwork": 0.6, "openness": 0.65},
        "responsibilities": [
            ("Write and review code", "Implement features and review peers' code.", 0.9),
            ("Design software systems", "Plan architectures that scale and last.", 0.8),
            ("Debug and test applications", "Find and fix defects; write automated tests.", 0.7),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Computer Science, Mathematics", False),
            ("degree", "Undergraduate degree", "Bachelor's in Computer Science or Software Engineering", False),
            ("certification", "Alternative path", "Bootcamps and self-study are also viable", True),
        ],
        "relations": [("data-scientist", "similar"), ("product-manager", "progression"), ("ai-researcher", "alternative")],
    },
    {
        "slug": "ai-researcher", "name": "AI / Machine Learning Researcher",
        "category": "Science", "subcategory": "Research",
        "summary": "Invents new algorithms that push AI forward.",
        "description": "AI researchers push the boundaries of what machines can learn, developing new algorithms and models.",
        "difficulty_level": "Advanced", "work_environment": "Lab / University / Office",
        "salary_range": "High", "outlook": "Excellent",
        "remote_friendly": False, "education_level": "Doctorate",
        "skills": _skills("Advanced mathematics", "Deep learning", "Research methodology", "Programming"),
        "subjects": ["Mathematics", "Computer Science", "Physics"],
        "industries": ["Artificial Intelligence", "Research"],
        "tools": ["Python", "TensorFlow", "Jupyter"],
        "traits": {"analytical_thinking": 0.95, "numerical_reasoning": 0.95, "problem_solving": 0.9,
                   "technology": 0.85, "openness": 0.85},
        "responsibilities": [
            ("Read and write research papers", "Stay at the frontier and publish findings.", 0.9),
            ("Design experiments", "Form and test hypotheses rigorously.", 0.85),
            ("Prototype novel models", "Implement and evaluate new architectures.", 0.8),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Mathematics, Computer Science, Physics", False),
            ("degree", "Undergraduate degree", "Bachelor's in Computer Science or related field", False),
            ("masters", "Postgraduate research", "Master's then PhD in ML or related fields", False),
        ],
        "relations": [("data-scientist", "similar"), ("software-engineer", "alternative")],
    },
    {
        "slug": "doctor", "name": "Medical Doctor",
        "category": "Healthcare", "subcategory": "Medicine",
        "summary": "Diagnoses and treats illness to care for patients.",
        "description": "Doctors diagnose and treat illness, caring for patients' physical and mental health.",
        "difficulty_level": "Advanced", "work_environment": "Hospital / Clinic",
        "salary_range": "High", "outlook": "Strong — stable demand",
        "remote_friendly": False, "education_level": "Doctorate (MBBS/MD)",
        "skills": _skills("Biology knowledge", "Empathy", "Decision making", "Communication"),
        "subjects": ["Biology", "Chemistry", "Physics"],
        "industries": ["Healthcare"],
        "tools": [],
        "traits": {"healthcare": 0.95, "helping_others": 0.9, "conscientiousness": 0.9,
                   "analytical_thinking": 0.75, "security": 0.6},
        "responsibilities": [
            ("Diagnose conditions", "Interpret symptoms, tests and history.", 0.9),
            ("Treat patients", "Plan and deliver appropriate care.", 0.85),
            ("Communicate with patients and families", "Explain diagnoses and options with care.", 0.7),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Biology, Chemistry, Physics", False),
            ("degree", "Medical degree", "MBBS / MD", False),
            ("license", "Internship & licensing", "Supervised internship and specialisation", False),
        ],
        "relations": [("nurse", "alternative"), ("psychologist", "similar")],
    },
    {
        "slug": "nurse", "name": "Registered Nurse",
        "category": "Healthcare", "subcategory": "Nursing",
        "summary": "Provides hands-on care at the heart of healthcare teams.",
        "description": "Nurses provide hands-on patient care, support treatment plans and are the backbone of healthcare teams.",
        "difficulty_level": "Intermediate", "work_environment": "Hospital / Clinic",
        "salary_range": "Medium", "outlook": "Strong",
        "remote_friendly": False, "education_level": "Diploma / Bachelor's",
        "skills": _skills("Patient care", "Empathy", "Teamwork", "Attention to detail"),
        "subjects": ["Biology", "Chemistry"],
        "industries": ["Healthcare"],
        "tools": [],
        "traits": {"healthcare": 0.9, "helping_others": 0.95, "teamwork": 0.8,
                   "conscientiousness": 0.8, "security": 0.6},
        "responsibilities": [
            ("Monitor patients", "Track vital signs and patient progress.", 0.9),
            ("Administer care and medication", "Deliver treatments safely and accurately.", 0.85),
            ("Support doctors and families", "Coordinate care and reassure families.", 0.7),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Biology, Chemistry", False),
            ("degree", "Nursing qualification", "Diploma or Bachelor's in Nursing", False),
            ("license", "Registration", "Register to practise", False),
        ],
        "relations": [("doctor", "progression"), ("psychologist", "similar")],
    },
    {
        "slug": "psychologist", "name": "Psychologist",
        "category": "Healthcare", "subcategory": "Mental Health",
        "summary": "Helps people improve their mental well-being.",
        "description": "Psychologists study behaviour and the mind, helping people improve their mental well-being.",
        "difficulty_level": "Advanced", "work_environment": "Clinic / Private practice",
        "salary_range": "Medium", "outlook": "Strong",
        "remote_friendly": True, "education_level": "Master's / Doctorate",
        "skills": _skills("Empathy", "Active listening", "Research", "Communication"),
        "subjects": ["Psychology", "Biology"],
        "industries": ["Healthcare", "Mental Health"],
        "tools": [],
        "traits": {"helping_others": 0.95, "healthcare": 0.6, "openness": 0.75,
                   "analytical_thinking": 0.7, "extraversion": 0.6},
        "responsibilities": [
            ("Assess clients", "Evaluate needs through interviews and tests.", 0.9),
            ("Provide therapy or counselling", "Support clients with evidence-based methods.", 0.85),
            ("Conduct behavioural research", "Study behaviour to improve practice.", 0.6),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Psychology, Biology", False),
            ("degree", "Undergraduate degree", "Bachelor's in Psychology", False),
            ("masters", "Postgraduate training", "Master's or Doctorate with supervised practice", False),
        ],
        "relations": [("doctor", "similar"), ("nurse", "similar"), ("teacher", "alternative")],
    },
    {
        "slug": "entrepreneur", "name": "Entrepreneur / Founder",
        "category": "Business", "subcategory": "Founders",
        "summary": "Builds businesses by turning ideas into value.",
        "description": "Entrepreneurs identify opportunities and build businesses, taking on risk to create new value.",
        "difficulty_level": "Advanced", "work_environment": "Dynamic / Varied",
        "salary_range": "Variable", "outlook": "High potential, high risk",
        "remote_friendly": True, "education_level": "Varies",
        "skills": _skills("Risk taking", "Leadership", "Selling", "Resilience"),
        "subjects": ["Business Studies", "Economics", "Mathematics"],
        "industries": ["Startups", "Technology"],
        "tools": ["Excel"],
        "traits": {"entrepreneurship": 0.98, "leadership": 0.85, "business": 0.85,
                   "openness": 0.75, "income": 0.7, "security": 0.2},
        "responsibilities": [
            ("Spot market opportunities", "Find unmet needs worth solving.", 0.9),
            ("Build and lead teams", "Hire, motivate and align people.", 0.8),
            ("Raise funding and grow ventures", "Secure resources and scale the business.", 0.7),
        ],
        "education": [
            ("degree", "Optional degree", "Business degrees help but are not required", True),
            ("certification", "Experience", "Initiative and hands-on experience matter most", False),
        ],
        "relations": [("product-manager", "alternative"), ("business-analyst", "similar"), ("marketing-manager", "similar")],
    },
    {
        "slug": "business-analyst", "name": "Business Analyst",
        "category": "Business", "subcategory": "Analytics",
        "summary": "Bridges data and decisions to improve how businesses run.",
        "description": "Business analysts bridge data and decisions, helping organisations work smarter and more profitably.",
        "difficulty_level": "Intermediate", "work_environment": "Office",
        "salary_range": "Medium-High", "outlook": "Strong",
        "remote_friendly": False, "education_level": "Bachelor's",
        "skills": _skills("Analytical thinking", "Communication", "Data literacy", "Domain knowledge"),
        "subjects": ["Economics", "Mathematics", "Business Studies"],
        "industries": ["Consulting", "Finance", "Professional Services"],
        "tools": ["Excel", "SQL", "Tableau"],
        "traits": {"analytical_thinking": 0.85, "business": 0.85, "numerical_reasoning": 0.75,
                   "teamwork": 0.65, "conscientiousness": 0.7},
        "responsibilities": [
            ("Analyse business processes", "Map how work flows and where it stalls.", 0.9),
            ("Interpret data", "Turn numbers into business meaning.", 0.8),
            ("Recommend improvements", "Propose changes that add value.", 0.7),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Economics, Mathematics, Business Studies", False),
            ("degree", "Undergraduate degree", "Bachelor's in Business, Economics or related field", False),
        ],
        "relations": [("data-scientist", "alternative"), ("product-manager", "progression"), ("entrepreneur", "similar")],
    },
    {
        "slug": "product-manager", "name": "Product Manager",
        "category": "Business", "subcategory": "Product",
        "summary": "Decides what to build and why, across design and engineering.",
        "description": "Product managers decide what to build and why, coordinating design, engineering and business.",
        "difficulty_level": "Advanced", "work_environment": "Office / Remote",
        "salary_range": "High", "outlook": "Strong",
        "remote_friendly": True, "education_level": "Bachelor's",
        "skills": _skills("Leadership", "Communication", "Analytical thinking", "Empathy for users"),
        "subjects": ["Business Studies", "Computer Science", "Economics"],
        "industries": ["Technology", "Software"],
        "tools": ["Excel", "Jira", "Figma"],
        "traits": {"leadership": 0.85, "business": 0.8, "technology": 0.6,
                   "extraversion": 0.65, "analytical_thinking": 0.7, "teamwork": 0.7},
        "responsibilities": [
            ("Define product strategy", "Set the vision and priorities.", 0.9),
            ("Prioritise features", "Decide what matters most for users and business.", 0.8),
            ("Coordinate cross-functional teams", "Align design, engineering and stakeholders.", 0.75),
        ],
        "education": [
            ("degree", "Undergraduate degree", "Business or technical degree", False),
            ("certification", "Product experience", "On-the-job product experience", False),
        ],
        "relations": [("software-engineer", "alternative"), ("business-analyst", "similar"), ("entrepreneur", "alternative")],
    },
    {
        "slug": "marketing-manager", "name": "Marketing Manager",
        "category": "Business", "subcategory": "Marketing",
        "summary": "Shapes how products reach and resonate with audiences.",
        "description": "Marketing managers shape how products reach and resonate with audiences.",
        "difficulty_level": "Intermediate", "work_environment": "Office",
        "salary_range": "Medium-High", "outlook": "Stable",
        "remote_friendly": False, "education_level": "Bachelor's",
        "skills": _skills("Creativity", "Communication", "Data analysis", "Persuasion"),
        "subjects": ["Business Studies", "Economics", "English"],
        "industries": ["Marketing", "Professional Services"],
        "tools": ["Excel", "PowerPoint"],
        "traits": {"business": 0.85, "arts": 0.6, "extraversion": 0.75,
                   "openness": 0.7, "leadership": 0.6},
        "responsibilities": [
            ("Plan campaigns", "Design campaigns that reach the right people.", 0.9),
            ("Understand customers", "Research what audiences need and want.", 0.8),
            ("Manage brand and growth", "Grow awareness and protect the brand.", 0.7),
        ],
        "education": [
            ("degree", "Undergraduate degree", "Bachelor's in Marketing, Business or Communications", False),
        ],
        "relations": [("entrepreneur", "similar"), ("product-manager", "similar")],
    },
    {
        "slug": "graphic-designer", "name": "Graphic / UX Designer",
        "category": "Arts & Design", "subcategory": "Design",
        "summary": "Crafts visuals and experiences that are beautiful and usable.",
        "description": "Designers craft visuals and experiences that are both beautiful and usable.",
        "difficulty_level": "Intermediate", "work_environment": "Studio / Remote",
        "salary_range": "Medium", "outlook": "Strong",
        "remote_friendly": True, "education_level": "Diploma / Bachelor's",
        "skills": _skills("Creativity", "Visual design", "Empathy", "Visual design tools"),
        "subjects": ["Art", "Computer Science", "Design"],
        "industries": ["Design", "Technology"],
        "tools": ["Figma"],
        "traits": {"arts": 0.95, "openness": 0.85, "technology": 0.55,
                   "teamwork": 0.6, "conscientiousness": 0.6},
        "responsibilities": [
            ("Design interfaces and graphics", "Create visuals and user interfaces.", 0.9),
            ("Prototype ideas", "Turn concepts into testable mockups.", 0.8),
            ("Collaborate with teams", "Work with product and engineering.", 0.65),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Art, Design, Computer Science", False),
            ("degree", "Design qualification", "Diploma or Bachelor's in Design", False),
            ("certification", "Portfolio", "Build a strong portfolio", False),
        ],
        "relations": [("product-manager", "similar"), ("software-engineer", "alternative"), ("marketing-manager", "similar")],
    },
    {
        "slug": "teacher", "name": "Teacher / Educator",
        "category": "Education", "subcategory": "Teaching",
        "summary": "Helps the next generation learn and grow.",
        "description": "Teachers shape the next generation, helping students learn and grow.",
        "difficulty_level": "Intermediate", "work_environment": "School / College",
        "salary_range": "Medium", "outlook": "Stable",
        "remote_friendly": False, "education_level": "Bachelor's + teaching qualification",
        "skills": _skills("Communication", "Patience", "Subject expertise", "Empathy"),
        "subjects": ["Any subject specialism", "Education"],
        "industries": ["Education"],
        "tools": [],
        "traits": {"helping_others": 0.9, "extraversion": 0.65, "conscientiousness": 0.75,
                   "openness": 0.6, "security": 0.6},
        "responsibilities": [
            ("Plan and deliver lessons", "Design and teach engaging lessons.", 0.9),
            ("Mentor students", "Guide and encourage learners.", 0.8),
            ("Assess progress", "Evaluate and support student growth.", 0.7),
        ],
        "education": [
            ("degree", "Undergraduate degree", "Bachelor's in the subject", False),
            ("certification", "Teaching qualification", "Teaching credential (e.g. B.Ed)", False),
        ],
        "relations": [("psychologist", "alternative"), ("nurse", "similar")],
    },
    {
        "slug": "civil-engineer", "name": "Civil Engineer",
        "category": "Engineering", "subcategory": "Civil & Structural",
        "summary": "Designs and builds the infrastructure of society.",
        "description": "Civil engineers design and build the infrastructure of society — roads, bridges and buildings.",
        "difficulty_level": "Intermediate", "work_environment": "Office / Site",
        "salary_range": "Medium-High", "outlook": "Stable",
        "remote_friendly": False, "education_level": "Bachelor's",
        "skills": _skills("Mathematics", "Problem solving", "Project management", "Attention to detail"),
        "subjects": ["Mathematics", "Physics"],
        "industries": ["Construction"],
        "tools": ["AutoCAD", "Excel"],
        "traits": {"numerical_reasoning": 0.85, "problem_solving": 0.85, "analytical_thinking": 0.8,
                   "conscientiousness": 0.8, "security": 0.6},
        "responsibilities": [
            ("Design structures", "Plan safe, efficient structures.", 0.9),
            ("Manage construction projects", "Coordinate timelines, budgets and teams.", 0.8),
            ("Ensure safety standards", "Verify work meets codes and safety.", 0.75),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Mathematics, Physics", False),
            ("degree", "Undergraduate degree", "Bachelor's in Civil Engineering", False),
            ("license", "Professional licensing", "Professional engineer licensing", False),
        ],
        "relations": [("software-engineer", "alternative"), ("business-analyst", "alternative")],
    },
    {
        "slug": "accountant", "name": "Accountant / Financial Analyst",
        "category": "Finance", "subcategory": "Accounting & Finance",
        "summary": "Manages and interprets the numbers that keep organisations healthy.",
        "description": "Accountants and financial analysts manage and interpret the numbers that keep organisations healthy.",
        "difficulty_level": "Intermediate", "work_environment": "Office",
        "salary_range": "Medium-High", "outlook": "Stable",
        "remote_friendly": False, "education_level": "Bachelor's + certification",
        "skills": _skills("Numerical reasoning", "Attention to detail", "Integrity", "Analysis"),
        "subjects": ["Mathematics", "Economics", "Accounting"],
        "industries": ["Finance", "Professional Services"],
        "tools": ["Excel"],
        "traits": {"numerical_reasoning": 0.95, "conscientiousness": 0.9, "analytical_thinking": 0.8,
                   "security": 0.75, "income": 0.6},
        "responsibilities": [
            ("Prepare financial reports", "Produce accurate financial statements.", 0.9),
            ("Analyse budgets", "Track spending and forecast finances.", 0.8),
            ("Ensure compliance", "Keep records compliant with regulations.", 0.75),
        ],
        "education": [
            ("secondary", "Secondary subjects", "Mathematics, Economics, Accounting", False),
            ("degree", "Undergraduate degree", "Bachelor's in Accounting or Finance", False),
            ("certification", "Professional certification", "Professional accounting certification", False),
        ],
        "relations": [("business-analyst", "similar"), ("entrepreneur", "alternative")],
    },
]
